### ISSUE TITLE
수강신청 조회 : 404 - 수강신청 정보 없음

### ISSUE THREAD

**Issue by happy7yong** [Chanj1019/Hip#83]
```
loading registrations for course 1 
HttpErrorResponse {headers: HttpHeaders, status: 404, statusText: 'Not Found', url: 'http://localhost:3000/courses/1/courseRegistration', ok: false, …}

{message: "수강 신청 정보가 없습니다.", error: "Not Found", statusCode: 404}
error
: 
"Not Found"
message
: 
"수강 신청 정보가 없습니다."
statusCode
: 
404
```
courseid : 1 잘간거 확인했으나, 수강신청 정보가 없다고 뜹니다

![sgs](https://github.com/user-attachments/assets/4d2f24ad-072c-4c4a-a6ae-a3475f3c1903)

이거 혹시 generation 때문일까요?

**Comment by rlawogh1005** [comment]
지금 course_registration.controller에서 findAllForAdmin() 메서드에 course_id를 받아오고 있지 않아서 발생한 문제로 보입니다. 수정할게요.

**Comment by happy7yong** [comment]
계속 수강정보를 받아오고 있지 못하고있씁니답.. 
![Uploading 화면 캡처 2024-11-04 160115.png…]()

**Comment by happy7yong** [comment]
![화면 캡처 2024-11-04 160115](https://github.com/user-attachments/assets/17948b93-7a14-4fe9-892f-3731d2bf0836)

**Comment by happy7yong** [comment]
이거 혹시 generation때문인가요 아직 프론트는 generation이 적용되어있지 않습니다.
