### ISSUE TITLE
비디오 주제 생성 에러 :  Internal Server Error

### ISSUE THREAD

**Issue by happy7yong** [Chanj1019/Hip#89]
비디오 주제 생성할때 데이터는 전송이 가능한데, Internal Server Error가 뜹니다. 

![image](https://github.com/user-attachments/assets/171b575e-982c-4daf-b698-168bf72240c8)

백엔드 프로젝트 파일에서 이런 오류가 생성동시에 뜹니다.
![image](https://github.com/user-attachments/assets/22727ce8-9d4a-4da7-a8b5-1d597b571e35)

**Comment by rlawogh1005** [comment]
이번 커밋에서 course, video topic, doc name, course doc에 대한 조회를 nested(계층형) json 형태로 반환되도록 수정 및 추가했습니다.
이후 Angular의 course.service.ts에서 엔드포인트 연결, classmy.page.ts와 classmy.html에서 이벤트를 연결하면 됩니다.
